package controllers;

public enum Commands {
	//REPORTS COMMANDS
	REPORT_ONE, REPORT_TWO, REPORT_THREE, REPORT_FOUR, REPORT_FIVE, REPORT_SIX, REPORT_SEVEN,REPORT_EIGHT,REPORT_NINE,REPORT_TEN,
	REFRESH, IMPORT, EXPORT, CANCEL, C_ES_LANGUAGE,ADD_PATIENT,REMOVE_PATIENT,CREATE_PATIENT, C_US_LANGUAGE, EXIT_APP;
}
